AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to create a DynamoDB table for a movie ranking application.

Resources:
  MoviesTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: "Movies"
      AttributeDefinitions:
        - AttributeName: "movieId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "movieId"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      Tags:
        - Key: "Environment"
          Value: "Production"
        - Key: "Application"
          Value: "MovieRankingApp"

Outputs:
  MoviesTableName:
    Description: "The name of the DynamoDB Movies table."
    Value: !Ref MoviesTable
